CA02: This is a eMail Spam Classifers that uses Naive Bayes supervised machine learning algorithm. 

In this assignment you will ...
1. Complete the code such a way that it works correctly with this given parts of the program.
2. Explain as clearly as possible what each part of the code is doing. Use "Markdown" texts and code commenting to explain the code

IMPORTANT NOTE:

The path of your data folders 'train-mails' and 'test-mails' must be './train-mails' and './test-mails'. This means you must have your .ipynb file and these folders in the SAME FOLDER in your laptop or Google Drive. The reason for doing this is, this way the peer reviewes and I would be able to run your code from our computers using this exact same relative path, irrespective of our folder hierarchy.

In [113]:
import os
import numpy as np
from collections import Counter

# Import all other necessary libraries. Your code below ...
import pandas as pd
import sklearn as sk
import numpy as np
import matplotlib.pyplot as plt
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [114]:
def make_Dictionary(root_dir):
    #Creates a empty matrix to store the values in 
  all_words = []
    #Stores the list of the paths of all of the email files in a variable
  emails = [os.path.join(root_dir,f) for f in os.listdir(root_dir)]
    #This for loop opens each email individually and then reads the email. As it is reading the email,
    # the loop will split the words and store them in all words (empty list established earlier.
  for mail in emails:
    with open(mail) as m:
      for line in m:
        words = line.split()
        all_words += words
    #Counter(all_words) counts the number of times each word occurs and then stores it in dictionary variable
  dictionary = Counter(all_words)
    #Converts the dictionary into a list of values that will eventually be removed  
  list_to_remove = list(dictionary)
#Loops through the list and removes all non-alphabetic words and single character words
  for item in list_to_remove:
    if item.isalpha() == False:
      del dictionary[item]
    elif len(item) == 1:
      del dictionary[item]
    #Selects the 3,000 most common words to use as features
  dictionary = dictionary.most_common(3000)
    #Returns the final dictionary of words
  return dictionary
            

In [115]:
def extract_features(mail_dir):
    #Extracts the paths for all emails and stroes them in the files variables
  files = [os.path.join(mail_dir,fi) for fi in os.listdir(mail_dir)]
    #Creates a matrix with the size of (number of emails x 3000) all with the value of 0
  features_matrix = np.zeros((len(files),3000))
    #Creates a matrix with the size of (number of emails) all with the value of 0
  train_labels = np.zeros(len(files))
    #Initiate counter variables
  count = 1;
  docID = 0;
    #Reads each email and updates feature vectors based on word occurances
  for fil in files:
    with open(fil) as fi:
      for i, line in enumerate(fi):
        if i ==2:
          words = line.split()
          for word in words:
            wordID = 0
              #If the current word is in the dictionary, it increments the corresponding feature
              #value.
            for i, d in enumerate(dictionary):
              if d[0] == word:
                wordID = i
                features_matrix[docID,wordID] = words.count(word)
        #Extracts the name of the file by splotting the path and considering only the last part of the path
      train_labels[docID] = 0;
        #If this program is being run on Windows change / to \\ in the split function below
      filepathTokens = fil.split('\\')
      lastToken = filepathTokens[len(filepathTokens)-1]
          #If the name of the file contains "spmsg" label it as a spam message
      if lastToken.startswith("spmsg"):
        train_labels[docID] = 1;
        count = count + 1
      docID = docID + 1
  return features_matrix, train_labels                

In [116]:
# Enter the "path" of your "train_mails" and "test-mails" FOLDERS in this cell ...
# for example: TRAIN_DIR = '../../train-mails'
#              TEST_DIR = '../../test-mails'

TRAIN_DIR = './train-mails'
TEST_DIR = './test-mails'

In [117]:
#Build the dictionary for the training data
dictionary = make_Dictionary(TRAIN_DIR)

print ("reading and processing emails from TRAIN and TEST folders")
#Extracting the feature matricies for the training and the test data
features_matrix, labels = extract_features(TRAIN_DIR)
test_features_matrix, test_labels = extract_features(TEST_DIR)

reading and processing emails from TRAIN and TEST folders


In [118]:
#Printing variables to check if the features were properly extracted and labeled
print(dictionary)

[('order', 1414), ('address', 1299), ('report', 1217), ('mail', 1133), ('language', 1099), ('send', 1080), ('email', 1066), ('program', 1009), ('our', 991), ('list', 946), ('one', 921), ('name', 883), ('receive', 826), ('free', 801), ('money', 797), ('work', 756), ('information', 684), ('business', 669), ('please', 657), ('university', 600), ('us', 567), ('day', 559), ('follow', 545), ('internet', 533), ('over', 514), ('call', 488), ('http', 479), ('check', 475), ('each', 466), ('linguistic', 460), ('include', 452), ('com', 450), ('want', 426), ('need', 426), ('number', 424), ('letter', 420), ('many', 412), ('here', 400), ('market', 398), ('start', 390), ('even', 388), ('fax', 384), ('form', 381), ('most', 377), ('first', 374), ('web', 372), ('service', 365), ('interest', 364), ('software', 362), ('read', 352), ('remove', 349), ('those', 346), ('week', 346), ('credit', 334), ('every', 333), ('site', 331), ('ll', 326), ('english', 325), ('edu', 319), ('much', 318), ('product', 318), ('b

In [119]:
print(labels)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [120]:
print(test_features_matrix)

[[ 1.  0.  0. ...  1.  0.  0.]
 [ 1.  1.  0. ...  0.  0.  0.]
 [ 1.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [17.  2.  0. ...  0.  0.  0.]]


In [121]:
print(test_labels)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [122]:
# In this section enter your code to TRAIN the model using Naive Bayes algorithm, then PREDICT and then evaluate PERFORMANCE (Accuracy)
# Your code below ...



#Training the Naive Bayes model using the training features and labels
model = MultinomialNB()
print("Training Model Using Gausian(Multinomial) Naive Bayes Algorithm")
model.fit(features_matrix, labels)
print("Training completed")

#Using the trained model, we can predict email classifications of the test values
print("Testing trained model to predict Test Data Labels")
y_pred=model.predict(test_features_matrix)
print("Completed classification of the Test Data")

#Print the accuracy score of the data
print(f"Now printing Accuracy Score by comparing the Predicted Labels with the Test Labels: {accuracy_score(test_labels,y_pred)*100}%")

# Your output should look like below if your code is right

Training Model Using Gausian(Multinomial) Naive Bayes Algorithm
Training completed
Testing trained model to predict Test Data Labels
Completed classification of the Test Data
Now printing Accuracy Score by comparing the Predicted Labels with the Test Labels: 96.15384615384616%


======================= END OF PROGRAM =========================